### ISSUE TITLE
"Say something..." a bit misleading when starting from scratch

### ISSUE THREAD

**Issue by blackary** [thesephist/merlot#1]
Enjoyed testing out the app, but when I first opened it up, and tried typing on the "Say something..." panel, and nothing worked, I was confused. Eventually I realized I needed to hit + to create a file. Would be good to have it prompt to create a new file, or create an untitled file by default if there aren't any yet if the user starts typing.

**Comment by thesephist** [comment]
Yeah, I got multiple pieces of feedback like this! Thanks for adding your voice to the pool :)

My fix (https://github.com/thesephist/merlot/commit/4bccc4dd951522ca5a5c4fa023ea69142896b791) was to add a "Welcome" file on first load of the app (if there isn't already data saved locally) that acts as (1) a place for users to start typing and editing, and (2) showcase what the app looks like in use. Just shipped it so I haven't heard much about it yet, but I expect it'll address that particular confusion you're talking about.

**Comment by blackary** [comment]
Looks great! Thanks, Linus.
